name: DevOps-GitHubActions
on: 
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: "root" # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ''
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
        #   cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
           name: java-app
           path: './target/*.jar'

  # Deploy Job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: '$/target/*.jar'
    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.TEST_CICD_SECRET }}
    #       publish_dir: ./build

